### ISSUE TITLE
-> WARNING: signal handler called for signal #11

### ISSUE THREAD

**Issue by khaledelmadawi** [stephanecharette/DarkHelp#42] opened 2023-12-26 05:06 UTC
I followed the instructions of building Darkhelp, running Darkhelp from terminal or from the example when it reaches
DarkHelp::NN::predict(), gives segmentation fault:
DarkHelp cfg/coco.names cfg/yolov4-tiny.cfg yolov4-tiny.weights artwork/dog.jpg

-> WARNING: signal handler called for signal #11

however darknet works correctly.

-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Building ver: 1.5.12-3
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
CMake Warning (dev) at /usr/local/lib/cmake/opencv4/OpenCVConfig.cmake:86 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

Call Stack (most recent call first):
  /usr/local/lib/cmake/opencv4/OpenCVConfig.cmake:108 (find_host_package)
  CM_dependencies.cmake:14 (FIND_PACKAGE)
  CMakeLists.txt:18 (INCLUDE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found CUDA: /usr/local/cuda-12.3 (found suitable exact version "12.3") 
-- Found OpenCV: /usr/local (found version "4.8.1") 
-- Configuring done (0.6s)
-- Generating done (0.0s)
-- Build files have been written to: /home/khalid/global_ws/DarkHelp/build

**Comment by stephanecharette** [comment] 2023-12-26 08:27
I just ran this command, and it looks like it is working for me:  `DarkHelp cfg/coco.names cfg/yolov4-tiny.cfg yolov4-tiny.weights artwork/dog.jpg`

Please provide more information so I can replicate your results, and also include the log file saved to /tmp/.

Also:  please provide the exact versions of Darknet and DarkHelp you are running, as well as the repo locations.

This is what it looks like when I run the command shown above with the latest version:

![image](https://github.com/stephanecharette/DarkHelp/assets/5061352/d62886fc-7e4a-4523-ba36-eafff271d564)

**Comment by khaledelmadawi** [comment] 2023-12-26 13:32
I am using Ubuntu22.04
-- Found CUDA: /usr/local/cuda-12.3 (found suitable exact version "12.3")
-- Found OpenCV: /usr/local (found version "4.8.1")(Built with GPU)
darkhelp version:
Building ver: 1.5.12-3
darknet version:
Darknet v2.0-63-g315c57b6-dirty
cuDNN version 12020 (v8.9.7)

what other info do you need?

**Comment by stephanecharette** [comment] 2023-12-26 14:11
> Darknet v2.0-63-g315c57b6-dirty

What did you modify in Darknet?  Run "git diff" or "git status" to see what files have changed.

> what other info do you need?

Note that it is working fine for me, as you can see above.  So I would need whatever is necessary to replicate the crash you are seeing.  At the very least, let's start with the things I mentioned in my previous comment.

**Comment by khaledelmadawi** [comment] 2023-12-26 14:33
I don't think I have made changes
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	build_old/
	predictions.jpg
	res.avi
	test.mp4

, but I will give it another try with different cuda and cudnn, can you share with me your configuration?

**Comment by stephanecharette** [comment] 2023-12-26 15:49
I have managed to reproduce the problem.  Fix is in progress.

**Comment by stephanecharette** [comment] 2023-12-26 16:03
Please see if the latest version of Darknet combined with the latest version of DarkHelp have solved the issue.

**Comment by khaledelmadawi** [comment] 2023-12-26 23:50
thanks for your effort, it works perfectly fine now :)

**Closed** 2024-01-11 09:47 UTC
